update

diff --git a/scripts/buildroot/data/beagleboneblue/rootfs-overlay/etc/init.d/S30wlan b/scripts/buildroot/data/beagleboneblue/rootfs-overlay/etc/init.d/S30wlan
--- a/scripts/buildroot/data/beagleboneblue/rootfs-overlay/etc/init.d/S30wlan
+++ b/scripts/buildroot/data/beagleboneblue/rootfs-overlay/etc/init.d/S30wlan
@@ -1,8 +1,30 @@
 #!/bin/sh
-set -e
+#
+# Start the wpa_supplicant....
+#
 
-printf "Connecting WLAN"
+mkdir -p /run/network
 
-wpa_supplicant -B -i wlan0 -c /etc/default/SSID.conf
+case "$1" in
+  start)
+	printf "Starting wpa_supplicant.. "
+	wpa_supplicant -B -i wlan0 -c /etc/default/SSID.conf
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	;;
+  stop)
+	printf "Stopping wpa_supplicant.. "
+	killall wpa_supplicant
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	;;
+  restart|reload)
+	"$0" stop
+	"$0" start
+	;;
+  *)
+	echo "Usage: $0 {start|stop|restart}"
+	exit 1
+esac
+
+exit $?
 
 #dhcpcd wlan0
